### ISSUE TITLE
Librem 5: HW VP9 decoder is unavailable

### ISSUE THREAD

**Issue by carlosgonz0** [Rafostar/clapper#232]
On gstreamer 1.21 and Linux 5.17 Clapper need to decoding vp9 by using v4l2 codecs, but it using vp9dec instead. Tried with Clapper Flatpak Nightly.

**Comment by carlosgonz0** [comment]
On gstreamer 1.21 and Linux 5.17 Clapper need to decoding vp9 by using v4l2 codecs, but it using vp9dec instead.

**Comment by carlosgonz0** [comment]
purism@pureos:~$ flatpak run --branch=master --command=sh com.github.rafostar.Clapper
[📦 com.github.rafostar.Clapper ~]$ gst-inspect-1.0 v4l2codecs
Plugin Details:
  Name                     v4l2codecs
  Description              V4L2 CODEC Accelerators plugin
  Filename                 /app/lib/gstreamer-1.0/libgstv4l2codecs.so
  Version                  1.21.0.1
  License                  LGPL
  Source module            gst-plugins-bad
  Binary package           GStreamer Bad Plug-ins git
  Origin URL               Unknown package origin

  v4l2slh264dec: V4L2 Stateless H.264 Video Decoder
  v4l2slmpeg2dec: V4L2 Stateless Mpeg2 Video Decoder
  v4l2slvp8alphadecodebin: VP8 Alpha Decoder
  v4l2slvp8dec: V4L2 Stateless VP8 Video Decoder

  4 features:
  +-- 4 elements

[📦 com.github.rafostar.Clapper ~]$

**Comment by Rafostar** [comment]
@carlosgonz0 

There is no `v4l2slvp9dec` on your available decoders list.

Try removing old cache `registry` bin file inside folder `~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0/`. While the file is still removed (first thing you do after removing it) run again:
```sh
flatpak run --branch=master --command=sh com.github.rafostar.Clapper
GST_DEBUG=v4l2*:7 gst-inspect-1.0 v4l2codecs
```

You need to run this while file is still removed, it will be rebuild and either rebuild might fix this on its own or maybe the `GST_DEBUG=v4l2*:7` debug output will say why VP9 is not being registered.

**Comment by carlosgonz0** [comment]
purism@pureos:~$ cd ~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0/
purism@pureos:~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0$ ls
registry.aarch64.bin
purism@pureos:~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0$ ls
registry.aarch64.bin
purism@pureos:~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0$ sudo rm -r registry.aarch64.bin
[sudo] password for purism: 
purism@pureos:~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0$ 
purism@pureos:~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0$ ls
purism@pureos:~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0$ flatpak run --branch=master --command=sh com.github.rafostar.Clapper
[📦 com.github.rafostar.Clapper gstreamer-1.0]$ GST_DEBUG=v4l2*:7 gst-inspect-1.0 v4l2codecs
0:00:00.041461202     4 0xaaaad9fb0e10 DEBUG             v4l2codecs gstv4l2codecdevice.c:331:gst_v4l2_codec_find_devices: Analysing media device '/dev/media0'
0:00:00.041642042     4 0xaaaad9fb0e10 DEBUG             v4l2codecs gstv4l2codecdevice.c:331:gst_v4l2_codec_find_devices: Analysing media device '/dev/media1'
0:00:00.041747042     4 0xaaaad9fb0e10 DEBUG             v4l2codecs gstv4l2codecdevice.c:331:gst_v4l2_codec_find_devices: Analysing media device '/dev/media2'
0:00:00.041784362     4 0xaaaad9fb0e10 DEBUG             v4l2codecs gstv4l2codecdevice.c:347:gst_v4l2_codec_find_devices: Found CODEC entities
0:00:00.041805242     4 0xaaaad9fb0e10 DEBUG             v4l2codecs gstv4l2codecdevice.c:357:gst_v4l2_codec_find_devices: Analysing entity nxp,imx8mq-vpu-dec-proc
0:00:00.041823842     4 0xaaaad9fb0e10 DEBUG             v4l2codecs gstv4l2codecdevice.c:362:gst_v4l2_codec_find_devices: Found source and sink pads
0:00:00.041841962     4 0xaaaad9fb0e10 DEBUG             v4l2codecs gstv4l2codecdevice.c:370:gst_v4l2_codec_find_devices: Found source and sink V4L IO entities
0:00:00.042082322     4 0xaaaad9fb0e10 INFO              v4l2codecs gstv4l2codecdevice.c:388:gst_v4l2_codec_find_devices: Found decoder device nxp,imx8mq-vpu-dec-proc
0:00:00.042532562     4 0xaaaad9fb0e10 DEBUG     v4l2codecs-decoder gstv4l2decoder.c:308:gst_v4l2_decoder_enum_sink_fmt:<v4l2decoder0> Found format MG2S (MPEG-2 Parsed Slice Data)
0:00:00.042564122     4 0xaaaad9fb0e10 INFO              v4l2codecs plugin.c:64:register_video_decoder:<v4l2decoder0> Registering nxp,imx8mq-vpu-dec-proc as Mpeg2 Decoder
0:00:00.043138562     4 0xaaaad9fb0e10 DEBUG     v4l2codecs-decoder gstv4l2decoder.c:308:gst_v4l2_decoder_enum_sink_fmt:<v4l2decoder0> Found format VP8F (VP8 Frame)
0:00:00.043175642     4 0xaaaad9fb0e10 INFO              v4l2codecs plugin.c:58:register_video_decoder:<v4l2decoder0> Registering nxp,imx8mq-vpu-dec-proc as VP8 Decoder
0:00:00.043704122     4 0xaaaad9fb0e10 DEBUG     v4l2codecs-decoder gstv4l2decoder.c:308:gst_v4l2_decoder_enum_sink_fmt:<v4l2decoder0> Found format S264 (H.264 Parsed Slice Data)
0:00:00.043746122     4 0xaaaad9fb0e10 INFO              v4l2codecs plugin.c:52:register_video_decoder:<v4l2decoder0> Registering nxp,imx8mq-vpu-dec-proc as H264 Decoder
0:00:00.458730859     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:132:gst_v4l2_probe_and_register: Probing devices
0:00:00.467458699     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:153:gst_v4l2_probe_and_register: Failed to get device capabilities: Inappropriate ioctl for device
0:00:00.471100699     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:153:gst_v4l2_probe_and_register: Failed to get device capabilities: Inappropriate ioctl for device
0:00:00.471361219     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:153:gst_v4l2_probe_and_register: Failed to get device capabilities: Inappropriate ioctl for device
0:00:00.471635899     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:153:gst_v4l2_probe_and_register: Failed to get device capabilities: Inappropriate ioctl for device
0:00:00.471837139     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:153:gst_v4l2_probe_and_register: Failed to get device capabilities: Inappropriate ioctl for device
0:00:00.472250659     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:153:gst_v4l2_probe_and_register: Failed to get device capabilities: Inappropriate ioctl for device
0:00:00.472480099     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:153:gst_v4l2_probe_and_register: Failed to get device capabilities: Inappropriate ioctl for device
0:00:00.473100499     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:165:gst_v4l2_probe_and_register: Probing 'hantro-vpu' located at '/dev/video2'
0:00:00.473131699     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:74:gst_v4l2_probe_template_caps: Getting /dev/video2 format enumerations
0:00:00.473163979     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:74:gst_v4l2_probe_template_caps: Getting /dev/video2 format enumerations
0:00:00.473193259     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:88:gst_v4l2_probe_template_caps: index:       0
0:00:00.473212339     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:89:gst_v4l2_probe_template_caps: type:        10
0:00:00.473231659     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:90:gst_v4l2_probe_template_caps: flags:       00000001
0:00:00.473257219     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:91:gst_v4l2_probe_template_caps: description: 'MPEG-2 Parsed Slice Data'
0:00:00.473285779     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:92:gst_v4l2_probe_template_caps: pixelformat: MG2S
0:00:00.473347819     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x5332474d MG2S
0:00:00.473385859     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:88:gst_v4l2_probe_template_caps: index:       1
0:00:00.473404219     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:89:gst_v4l2_probe_template_caps: type:        10
0:00:00.473422099     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:90:gst_v4l2_probe_template_caps: flags:       00000001
0:00:00.473439379     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:91:gst_v4l2_probe_template_caps: description: 'VP8 Frame'
0:00:00.473461099     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:92:gst_v4l2_probe_template_caps: pixelformat: VP8F
0:00:00.473484859     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x46385056 VP8F
0:00:00.473509459     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:88:gst_v4l2_probe_template_caps: index:       2
0:00:00.473527699     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:89:gst_v4l2_probe_template_caps: type:        10
0:00:00.473546539     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:90:gst_v4l2_probe_template_caps: flags:       00000001
0:00:00.473564779     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:91:gst_v4l2_probe_template_caps: description: 'H.264 Parsed Slice Data'
0:00:00.473585899     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:92:gst_v4l2_probe_template_caps: pixelformat: S264
0:00:00.473611579     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x34363253 S264
0:00:00.473646019     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:74:gst_v4l2_probe_template_caps: Getting /dev/video2 format enumerations
0:00:00.473668459     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2.c:74:gst_v4l2_probe_template_caps: Getting /dev/video2 format enumerations
0:00:00.473690779     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:88:gst_v4l2_probe_template_caps: index:       0
0:00:00.473708299     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:89:gst_v4l2_probe_template_caps: type:        9
0:00:00.473725699     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:90:gst_v4l2_probe_template_caps: flags:       00000000
0:00:00.473743219     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:91:gst_v4l2_probe_template_caps: description: 'Y/CbCr 4:2:0'
0:00:00.473763979     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:92:gst_v4l2_probe_template_caps: pixelformat: NV12
0:00:00.473822419     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:88:gst_v4l2_probe_template_caps: index:       1
0:00:00.473846659     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:89:gst_v4l2_probe_template_caps: type:        9
0:00:00.473869939     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:90:gst_v4l2_probe_template_caps: flags:       00000000
0:00:00.473892139     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:91:gst_v4l2_probe_template_caps: description: 'YUYV 4:2:2'
0:00:00.473918179     4 0xaaaad9fb0e10 LOG                     v4l2 gstv4l2.c:92:gst_v4l2_probe_template_caps: pixelformat: YUYV
0:00:00.474556340     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x31424752 RGB1
0:00:00.474595100     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x35315241 AR15
0:00:00.474647660     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0xb5315241 AR1.
0:00:00.474710060     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x52424752 RGBR
0:00:00.474741140     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x48524742 BGRH
0:00:00.474880820     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x34343452 R444
0:00:00.475000460     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x20343059 Y04 
0:00:00.475031060     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x20363059 Y06 
0:00:00.475059500     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x20303159 Y10 
0:00:00.475087100     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x20323159 Y12 
0:00:00.475136540     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x42303159 Y10B
0:00:00.475165940     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x384c4150 PAL8
0:00:00.475194500     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x20385655 UV8 
0:00:00.475243700     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x31324d59 YM21
0:00:00.475292180     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x56555959 YYUV
0:00:00.475341500     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x59555956 VYUY
0:00:00.475408460     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x50313459 Y41P
0:00:00.475438460     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x34343459 Y444
0:00:00.475467140     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x4f565559 YUVO
0:00:00.475495100     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x50565559 YUVP
0:00:00.475523180     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x34565559 YUV4
0:00:00.475580060     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x34324948 HI24
0:00:00.475609340     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x32314d48 HM12
0:00:00.475637540     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x3032344d M420
0:00:00.475705820     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x32314d56 VM12
0:00:00.475811900     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x3234564e NV42
0:00:00.475896020     4 0xaaaad9fb0e10 DEBUG                   v4l2 gstv4l2object.c:1592:gst_v4l2_object_v4l2fourcc_to_bare_struct: Unsupported fourcc 0x3436324d M264
Plugin Details:
  Name                     v4l2codecs
  Description              V4L2 CODEC Accelerators plugin
  Filename                 /app/lib/gstreamer-1.0/libgstv4l2codecs.so
  Version                  1.21.0.1
  License                  LGPL
  Source module            gst-plugins-bad
  Binary package           GStreamer Bad Plug-ins git
  Origin URL               Unknown package origin

  v4l2slh264dec: V4L2 Stateless H.264 Video Decoder
  v4l2slmpeg2dec: V4L2 Stateless Mpeg2 Video Decoder
  v4l2slvp8alphadecodebin: VP8 Alpha Decoder
  v4l2slvp8dec: V4L2 Stateless VP8 Video Decoder

  4 features:
  +-- 4 elements

[📦 com.github.rafostar.Clapper gstreamer-1.0]$

**Comment by Rafostar** [comment]
It does not even try to register VP9. You sure your HW can do VP9? If yes, please ask GStreamer devs about this, as there is nothing wrong with Clapper here. Its just GStreamer does not register `v4l2slvp9dec` element on your device.

**Comment by carlosgonz0** [comment]
Yes Librem 5 has a VPU to decode vp9: https://www.nxp.com/products/processors-and-microcontrollers/arm-processors/i-mx-applications-processors/i-mx-8-processors/i-mx-8m-family-armcortex-a53-cortex-m4-audio-voice-video:i.MX8M

https://www.phoronix.com/scan.php?page=news_item&px=Hantro-VP9-Linux-5.17

https://gstreamer.freedesktop.org/releases/1.20/

**Comment by carlosgonz0** [comment]
Maybe Purism need to enable something on the kernel?

**Comment by Rafostar** [comment]
Clapper Flatpak Nightly includes latest gnome-nightly runtime and builds latest GStreamer from git. If GStreamer does not find VP9 acceleration support on your device, then there is nothing I can do about this here.

**Comment by Rafostar** [comment]
> as the v4l2slh264dec already work on L5 and Clapper

This is not about Clapper not working with VP9. Its about GStreamer not offering VP9 HW decoder on L5 for some reason. That is why this cannot be fixed here.

**Comment by carlosgonz0** [comment]
Yes i fully understand that this issues it not for Clapper but for gstreamer. I thankfully with you for all the help that you did. I going troubleshooting with Gstreamer and hantro g2 linux.
Thank you @Rafostar

**Comment by carlosgonz0** [comment]
@Rafostar do you have a link to donate you?

**Comment by Rafostar** [comment]
You can find sponsor/donation links on Clapper GitHub main page. All donations and contributions are appreciated.

**Comment by Rafostar** [comment]
> do you have a link to donate you?

If you want to help with donation you can either use https://liberapay.com/Clapper or paypal http://paypal.me/Rafostar

**Comment by carlosgonz0** [comment]
purism@pureos:~$ uname -ra
Linux pureos 5.17.0-1-librem5 #1 SMP PREEMPT Tue Apr 12 13:08:15 UTC 2022 aarch64 GNU/Linux
purism@pureos:~$ lsmod | grep -i hantro
hantro_vpu            135168  0
v4l2_vp9               24576  1 hantro_vpu
v4l2_h264              16384  1 hantro_vpu
v4l2_mem2mem           40960  1 hantro_vpu
videobuf2_vmalloc      20480  1 hantro_vpu

**Comment by carlosgonz0** [comment]
> > do you have a link to donate you?
> 
> If you want to help with donation you can either use https://liberapay.com/Clapper or paypal http://paypal.me/Rafostar

Done: 9EG257853V9*****8

**Comment by carlosgonz0** [comment]
@Rafostar so this bug related to Gstreamer  seems it is fixed on gestreamer 1.20.1 so can you ship this gstreamer version to test it?

**Comment by Rafostar** [comment]
> Done

Thanks for contributing to the project. Appreciated.

> so this bug related to Gstreamer seems it is fixed on Gstreamer 1.20.1 so can you ship this Gstreamer version to test it?

I am including 1.20.1 in Flathub version since recently. Please try and let me know if issue is still there.

**Comment by carlosgonz0** [comment]
Same it is not work. :  /

Plugin Details:
  Name                     v4l2codecs
  Description              V4L2 CODEC Accelerators plugin
  Filename                 /app/lib/gstreamer-1.0/libgstv4l2codecs.so
  Version                  1.20.1
  License                  LGPL
  Source module            gst-plugins-bad
  Source release date      2022-03-14
  Binary package           GStreamer Bad Plug-ins source release
  Origin URL               Unknown package origin

  v4l2slh264dec: V4L2 Stateless H.264 Video Decoder
  v4l2slmpeg2dec: V4L2 Stateless Mpeg2 Video Decoder
  v4l2slvp8alphadecodebin: VP8 Alpha Decoder
  v4l2slvp8dec: V4L2 Stateless VP8 Video Decoder

  4 features:
  +-- 4 elements

[📦 com.github.rafostar.Clapper ~]$

**Comment by carlosgonz0** [comment]
Seems it is bug for hantro to Librem 5, so it not Gstreamer. I will testing clapper and hantro for pinephone rockchip.

**Comment by carlosgonz0** [comment]
Yes Yes Yes Yes Nice Nice it work now.

purism@pureos:~$ flatpak run --command=sh com.github.rafostar.Clapper
[📦 com.github.rafostar.Clapper ~]$ GST_DEBUG=v4l2*:7 gst-inspect-1.0 v4l2codecs
Plugin Details:
  Name                     v4l2codecs
  Description              V4L2 CODEC Accelerators plugin
  Filename                 /app/lib/gstreamer-1.0/libgstv4l2codecs.so
  Version                  1.20.1
  License                  LGPL
  Source module            gst-plugins-bad
  Source release date      2022-03-14
  Binary package           GStreamer Bad Plug-ins source release
  Origin URL               Unknown package origin

  v4l2slh264dec: V4L2 Stateless H.264 Video Decoder
  v4l2slmpeg2dec: V4L2 Stateless Mpeg2 Video Decoder
  v4l2slvp8alphadecodebin: VP8 Alpha Decoder
  v4l2slvp8dec: V4L2 Stateless VP8 Video Decoder
  v4l2slvp9alphadecodebin: VP9 Alpha Decoder
  v4l2slvp9dec: V4L2 Stateless VP9 Video Decoder

  6 features:
  +-- 6 elements

[📦 com.github.rafostar.Clapper ~]$
